### ISSUE TITLE
Change plugin directory

### ISSUE THREAD

**Issue by sunshineo** [tutumcloud/wordpress-stackable#23]
Current plugin directory is /app/wp-content/plugins
I want to change to /app/plugins
According to
https://codex.wordpress.org/Editing_wp-config.php#Moving_plugin_folder
All I need to do is
define( 'WP_PLUGIN_DIR', '/app/plugins' );
So I added this in my Dockerfile
RUN sudo echo "define( 'WP_PLUGIN_DIR', '/app/plugins' );" >> /app/wp-config.php

The echo worked. But the WP_PLUGIN_DIR setting does not take effect. Did this project do something special to where wordpress load plugins?

Thank you very much!

**Comment by Tebro** [comment]
Why do you want to move it? Only wp-content is a volume so only that gets kept if you redeploy the image.

**Comment by sunshineo** [comment]
I exactly want it to not keep it when I redeploy. I manage my plugins off line using source control

**Comment by sunshineo** [comment]
Also, one more thing. I wrote a script to automatically download WordPress plugins. I try to use it during docker build. It does not work because it is a volume.
https://github.com/docker/docker/issues/13117
https://github.com/docker/docker/issues/3639

**Comment by sunshineo** [comment]
My full docker file. I feel WP did not really make it easy to move the plugin folder around.

FROM tutum/wordpress-stackable:latest

RUN sudo mkdir /app/plugins
WORKDIR /app/plugins

# The base does not have unzip unfortunately
RUN sudo apt-get update
RUN sudo apt-get install -qq zip
RUN sudo apt-get install -qq unzip

RUN sudo echo "define( 'WP_PLUGIN_DIR', '/app/plugins' );" >> /app/wp-config.php
RUN sudo echo "define( 'WP_PLUGIN_URL', 'http://192.168.59.103/wp-content/plugins' );" >> /app/wp-config.php
RUN sudo echo "define( 'PLUGINDIR', '/app/plugins' );" >> /app/wp-config.php

# Think of this file as: bower.json
ADD plugins.txt ./

# Think of the below as: npm install bower
# https://github.com/sunshineo/wppatm
RUN curl -sSLO https://raw.githubusercontent.com/sunshineo/wppatm/master/install.sh
RUN chmod +x install.sh

# Think of the below as: bower install
RUN ./install.sh

RUN sudo chmod +777 /app/plugins
RUN sudo cp /app/wp-content/plugins/index.php /app/plugins

**Comment by sunshineo** [comment]
This is totally wordpress issue.

I cannot add the config at the bottom of the file, it is too late. Configuration after
```
89 /** Sets up WordPress vars and included files. */
90 require_once(ABSPATH . 'wp-settings.php');
```
will not work at all.

In the wp-settings.php
```
32 // Set initial default constants including WP_MEMORY_LIMIT, WP_MAX_MEMORY_LIMIT, WP_DEBUG, WP_CONTENT_DIR and WP_CACHE.
33 wp_initial_constants();
```

Anything after this line will not work.

**Comment by sunshineo** [comment]
However, I still cannot figure out what to set for WP_CONTENT_URL

I tried:
define( 'WP_CONTENT_DIR', '/app/blog/wp-content' );

define( 'WP_CONTENT_URL', 'http://'. $_SERVER['HTTP_HOST'] . '/blog/wp-content' );
define( 'WP_CONTENT_URL', 'http://localhost/blog/wp-content' );
define( 'WP_CONTENT_URL', 'http://192.168.59.103 /blog/wp-content' ); // my boot2docker ip
define( 'WP_CONTENT_URL', 'http://192.168.5.116 /blog/wp-content' );  // my docker ip

Simply does not work

**Comment by sunshineo** [comment]
https://wordpress.org/support/topic/cannot-properly-configure-wp_content_url
