### ISSUE TITLE
Fixed version of Wordpress?

### ISSUE THREAD

**Issue by spicypixel-** [tutumcloud/wordpress-stackable#24]
I've noticed that it's pulling Wordpress 4.1.1 rather than the latest tarball. Is this by design?

**Comment by sunshineo** [comment]
Yes. https://github.com/tutumcloud/tutum-docker-wordpress-nosql/blob/master/Dockerfile#L4
I forked it and upgraded to 4.2.2 https://github.com/sunshineo/tutum-docker-wordpress-nosql
docker image https://registry.hub.docker.com/u/sunshineo/tutum-docker-wordpress-nosql/

But I also removed the volume, which may not be what you want.
https://github.com/sunshineo/tutum-docker-wordpress-nosql/commit/c14f1827e32bfe20f1be2a1a058907a9477ef97b
The reason I removed it is I'm using https://github.com/sunshineo/wppatm to manage plugin and themes . I don't want the volume to persist anything. I build a docker image each time I change any plugin or themes.
Example: https://github.com/sunshineo/wordpress-base

**Comment by tifayuki** [comment]
Even thought we put the latest tarball in the docker file. The image itself is not built automatically when there is a new release on wordpress.

This image has auto build enabled, which means docker hub will build the image whenever there is a new commit to master branch. So, bump version in Dockerfile do all the work.

PS: a PR to bump the version of wordpress is always welcomed :)

**Comment by tifayuki** [comment]
upgraded to 4.2.2
